---
title: "Introduction to `transclust`"
subtitle: "BIOINF 576: Tool Development for Bioinformatics"
author: "Abhirath Anand"
date: 2025-04-14
date-format: long
format:
    revealjs:
       slide-number: true
       theme: default
       incremental: true
---

## Motivation

- Epidemiology is the study of how diseases affect the health and illness of populations.
- Studying the transmission of infectious diseases is crucial for understanding their spread and controlling outbreaks.
- Whole genome sequencing (WGS) is a powerful tool for studying the genetic diversity of pathogens and their transmission dynamics.

## How do we study transmission?

- **Transmission clusters** are groups of individuals who are likely to be linked by a common source of infection or transmission.
- Why are clusters important?
  - They can help identify potential sources of outbreaks.
  - They can inform public health interventions and control measures.
  - They can provide insights into the evolution and spread of pathogens.

## How do we identify clusters?

- We can use genomic and epidemiological data.
- One of the most common methods for designating two isolates as part of the same transmission cluster is to use a **genomic distance threshold**.
- This threshold is often based on the number of single nucleotide polymorphisms (SNPs) between two genomes.
