// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// computeSharedMatrix
NumericMatrix computeSharedMatrix(CharacterMatrix dna_aln, int out_group);
RcppExport SEXP _transclust_computeSharedMatrix(SEXP dna_alnSEXP, SEXP out_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type dna_aln(dna_alnSEXP);
    Rcpp::traits::input_parameter< int >::type out_group(out_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSharedMatrix(dna_aln, out_group));
    return rcpp_result_gen;
END_RCPP
}
// computeDefiningVariants
std::vector<int> computeDefiningVariants(CharacterMatrix dna_aln, CharacterVector isolate_names, List subtrees);
RcppExport SEXP _transclust_computeDefiningVariants(SEXP dna_alnSEXP, SEXP isolate_namesSEXP, SEXP subtreesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type dna_aln(dna_alnSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type isolate_names(isolate_namesSEXP);
    Rcpp::traits::input_parameter< List >::type subtrees(subtreesSEXP);
    rcpp_result_gen = Rcpp::wrap(computeDefiningVariants(dna_aln, isolate_names, subtrees));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_transclust_computeSharedMatrix", (DL_FUNC) &_transclust_computeSharedMatrix, 2},
    {"_transclust_computeDefiningVariants", (DL_FUNC) &_transclust_computeDefiningVariants, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_transclust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
