# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the shared variant matrix
#'
#' @param dna_aln A matrix of DNA sequences (character matrix).
#' @param out_group The index of the outgroup isolate (1-based).
#'
#' @return A matrix of shared variants, where each element represents the number
#'         of shared variants between two isolates, with the diagonal set to Inf.
computeSharedMatrix <- function(dna_aln, out_group) {
    .Call(`_transclust_computeSharedMatrix`, dna_aln, out_group)
}

#' Compute the defining variants for each subtree
#'
#' @param dna_aln A matrix of DNA sequences (character matrix).
#' @param isolate_names A vector of isolate names (character vector).
#' @param subtrees A list of subtrees (phylo objects).
#'
#' @return A vector of integers representing the number of defining variants
#'         for each subtree.
computeDefiningVariants <- function(dna_aln, isolate_names, subtrees) {
    .Call(`_transclust_computeDefiningVariants`, dna_aln, isolate_names, subtrees)
}

