# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the shared variant matrix
#'
#' @param dna_character_matrix A matrix of DNA sequences (`CharacterMatrix`).
#' @param out_group The index of the outgroup isolate (1-based).
#'
#' @return A `NumericMatrix` of shared variants, where each element represents the
#'         number of shared variants between two isolates, with the diagonal set to Inf.
#' @noRd
computeSharedMatrix <- function(dna_character_matrix, out_group) {
    .Call(`_transclust_computeSharedMatrix`, dna_character_matrix, out_group)
}

#' Compute the defining variants for each subtree
#'
#' @param dna_character_matrix A matrix of DNA sequences (`CharacterMatrix`).
#' @param isolate_names A vector of isolate names (`CharacterVector`).
#' @param subtrees A list of subtrees (`phylo` objects).
#'
#' @return An `IntegerVector` of integers representing the number of defining
#'         variants for each subtree.
#' @noRd
computeDefiningVariants <- function(dna_character_matrix, isolate_names, subtrees) {
    .Call(`_transclust_computeDefiningVariants`, dna_character_matrix, isolate_names, subtrees)
}

