# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeSharedMatrix <- function(dna_aln, out_group) {
    .Call(`_transclust_computeSharedMatrix`, dna_aln, out_group)
}

computeDefiningVariants <- function(dna_aln, isolate_names, subtrees) {
    .Call(`_transclust_computeDefiningVariants`, dna_aln, isolate_names, subtrees)
}

