# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples

on:
  push:
    branches: [main]
  pull_request:

name: format-check.yaml

permissions: read-all

jobs:
  format-check:
    name: format-check
    runs-on: ubuntu-latest
    concurrency:
      group: format-check-${{ github.event_name != 'pull_request' || github.run_id }}
    steps:
      - uses: actions/checkout@v5

      - name: Install
        uses: posit-dev/setup-air@v1

      - name: Check
        run: air format . --check